<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="being_a_casino_is_no_longer_enough.aspx.cs" Inherits="being_a_casino_is_no_longer_enough" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <title>Eurasia - Oppotunities and issues</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <BR /><BR /><BR /><BR /><BR /><BR />
<div id="PageContainerOuter">
	<div id="PageContainer">
		<div id="HomeColumn2">
			<div id="HomeGallery">
				<div id="Detail">
					<div id="DetailHeader"></div>
					<div id="DetailCopy">
						<span class="style1">
							Population Growth Demand Exceeding Infrastructure Supply
						</span>
						<br/><br />
						A simple look at official U.S. Census figures tells the story in black and white. In 1980, Clark Count boasted a population of a bit over half a million. By 2010, the population was slightly more than 2,000,000, a gain of roughly 400 percent.
						<br/><br />
						Many of these new arrivals aren't in the gaming industry. They're white collar employees of the numerous new and relocated light-manufacturing, warehousing and other companies attracted to the valley by Nevada's favorable tax policies, reasonable property values, miles and miles of room for expansion and easy freeway and rail access to major shipping points.
						<br/><br />
						And many of these new managers and workers are young couples with children. Children that are enrolling in school faster than the county's educational system can expand to accommodate them. Children who are overtaxing the few available organized extra-curricular and recreational activities available. Meanwhile, Clark County's foreclosure, bankruptcy and unemployment rates began to soar.
						<br/><br />
						Than came the financial crash. The housing market collapsed. Even casinos had, in some cases, to lower room rates and lay off staff. Other industries followed. Residential property values nose dived and the subsequent drop in assessed valuations killed the possibility of properly financing school upgrades and expansion via growth in real estate tax collections.
						<br/><br />
						Did you know that the top echelon of Eurasia's management team are all turnaround specialists? Not in the sense of people who come into a dying business, change its business model and attitudes and return it to profit, though we occasionally do some of those things.
						<br/><br />
						But those are the small projects, projects that don't offer the huge profits and public-service rewards of creating new commercial worlds, of changing a community's culture for the better, of turning around an entire industry instead of a single company.
						<br/><br />
						In Las Vegas, the Eurasia project offers a true Win! Win! Win! Win! scenario.
						<br/><br />
						We and our shareholders will win by getting rich on the massive appreciation in share prices that will accompany every new addition and renovation that's completed on time and under budget.
						<br/>
						<ul class="gallery">
							<li><img src="images2/p1_chapter_3.jpg" alt="New School for Us? It's about time" width="200px"></li>
						</ul>
						Clark County and the whole Las Vegas region will win because of the vast increase in tax revenues, gaming income, and retail sales generated by the estimated 60 millions new annual visitors Eurasia will bring to Las Vegas.
						<br/><br />
						Sixty million new visitors who will return regularly and often... who will return three, four, five or more times a year to shop in Eurasia's 5,400,000 square foot retail paradise, to attend our two annual Formula One races and the other major events at the new 20,000-seat Coliseum.
						<br/><br />
						Sports Arena, to wine, dine, go to shows and gamble at one of our 38-immersively detailed country-specific casinos.
						<br/><br />
						Sixty million visitors who will come to marvel at our world-class cirque-style entertainments and ride the world's tallets (800 feet) and most magnificient Ferris Wheel, the world's only "green" Ferris Wheel, powered entirely, as is much of the Eurasia project, by wind, solar and other environmentally friendly energy sources.
						<br/><br />
						Sixty million visitors who will come to watch and perhaps win a chance to participate in one of the dozens of television dramas, game shows, reality shows, soap operas and feature films in production 24/7/365 at Eurasia's Fantazmus Studios.
						<br/><br />
						The people... all the people... everyone in Las Vegas, whether working in the gaming industry or not, will win because of the 250,000 new permanent job this project will create, because of the community-wide financial turnaround it will enable.
						<br/><br />
						A financial turnaround that will reduce Clark County's untenably high foreclosure, bankruptcy and unemployment rates by 90-plus percent.
						<br/><br />
						Other Eurasia development winners? The most important winners? Children... all the children of Las Vegas, Clark County and surrounding areas.
						<br/><br />
						As our prime education initiative, we will establish and fund a Foundation to build and manage the Palace of the Little Angels, an after school and weekend cultural activity, learning and events center.
						<br/><br />
						This foundation, under a board of directors composed of internationally known educators and local teachers and parents, will set a new educational/recreational standard, enhancing the lives and spurring the intellectual and physical development of tomorrow's winners by providing an enriched cultural environment encompassing a Performing Arts Palace Theater, state of the art multimedia laboratories, indoor gymnasiums and sports training facilities, and outdoor playing fields for both casual and organized sport competitions.
						<br/><br />
						The Palace, designed to emulate aspects of Michelangelos's late Roman buildings, particularly St. Peter's Basilica, will be protected by a hybrid security system featuring state-of-the-art electronic instrusion and warning systems and highly paid security professionals well trained to neutralize both external threats and internal corruptive influences such as drug and alcohol use.
					</div>
				</div>
			</div>
			<div id="TwitterFeedHeader"></div>
			<div id="TwitterFeedContainer" style="width: 380px;  padding: 0px 0px 10px 70px; height: 87px; "
			<!-- <a title="Live the M life" rel="lightbox[southchapel]" href="peelad/interior_popup.swf?width=252&amp;height=525"><img src="images/home/Mlife-Banner.jpg" width="300" height="87" border="0" style="margin: 0px; float: left;"/></a> -->
			</div>
			<div class="HomePageRule"></div>
			<!-- Twitter Feed -->
			<div id="TwitterFeedContainer"><img src="images/btn-Twitter-on.jpg">
				<span id="lblDisplayTweet_LblTweet"> 
					<p>#FF #GlobalLtd @MarginInvestors @PennyStock @AcesOfACTS </p>
				</span>
			</div>
			<!-- /Twitter Feed -->	
			<div class="HomePageRule"><img src="images/spacer_002.gif" height="1" width="470"></div>
			<!-- Facebook Feed -->
			<div id="TwitterFeedContainer"></div>
			<!-- /Facebook Feed -->
			<div class="HomePageRule"></div>
			<div id="TwitterFeedViewAllNews" style="float: right;"></div>
		</div><!-- /Twitter Feed -->	
	</div>
</div>
</asp:Content>